"""
Alembic migration script to convert userstory_status from String to Enum.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250629_userstory_status_enum'
down_revision = 'dad69b01bdb8'  # Cambia esto por la última migración real si existe
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userstories', 'userstory_status',
        existing_type=sa.String(length=50),
        type_=sa.Enum('Pendiente', 'En Progreso', 'Finalizada', name='userstory_status_enum'),
        existing_nullable=False,
        server_default='Pendiente',
    )
    # ### end Alembic commands ###

def downgrade():
    op.alter_column('userstories', 'userstory_status',
        existing_type=sa.Enum('Pendiente', 'En Progreso', 'Finalizada', name='userstory_status_enum'),
        type_=sa.String(length=50),
        existing_nullable=False,
        server_default='Pendiente',
    )
