"""create initial tables

Revision ID: dad69b01bdb8
Revises: 
Create Date: 2025-06-29 12:39:20.419919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad69b01bdb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyects',
    sa.Column('proyect_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyect_name', sa.String(length=250), nullable=False),
    sa.Column('proyect_description', sa.String(length=2048), nullable=False),
    sa.Column('proyect_file_structure', sa.Text(), nullable=False),
    sa.Column('proyect_stack', sa.Text(), nullable=False),
    sa.Column('proyect_estimated_hours', sa.Integer(), nullable=False),
    sa.Column('proyect_start_date', sa.Date(), nullable=False),
    sa.Column('proyect_end_date', sa.Date(), nullable=False),
    sa.Column('project_manager', sa.String(length=100), nullable=False),
    sa.Column('proyect_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('proyect_id')
    )
    op.create_table('userstories',
    sa.Column('userstory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userstory_name', sa.String(length=250), nullable=False),
    sa.Column('userstory_description', sa.String(length=2048), nullable=False),
    sa.Column('userstory_role', sa.String(length=100), nullable=False),
    sa.Column('userstory_goal', sa.String(length=250), nullable=False),
    sa.Column('userstory_reason', sa.String(length=250), nullable=False),
    sa.Column('userstory_status', sa.String(length=50), nullable=False),
    sa.Column('userstory_priority', sa.String(length=50), nullable=False),
    sa.Column('userstory_estimated_points', sa.Integer(), nullable=False),
    sa.Column('userstory_estimated_time', sa.Integer(), nullable=False),
    sa.Column('userstory_actual_time', sa.Integer(), nullable=False),
    sa.Column('userstory_project_id', sa.Integer(), nullable=False),
    sa.Column('userstory_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('userstory_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userstory_project_id'], ['proyects.proyect_id'], ),
    sa.PrimaryKeyConstraint('userstory_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=250), nullable=False),
    sa.Column('task_description', sa.String(length=2048), nullable=False),
    sa.Column('task_status', sa.String(length=50), nullable=False),
    sa.Column('task_priority', sa.String(length=50), nullable=False),
    sa.Column('task_assigned_to', sa.String(length=100), nullable=False),
    sa.Column('task_estimated_time', sa.Integer(), nullable=False),
    sa.Column('task_actual_time', sa.Integer(), nullable=False),
    sa.Column('task_userstory_id', sa.Integer(), nullable=False),
    sa.Column('task_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_userstory_id'], ['userstories.userstory_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # Ampliar el tamaño de version_num en alembic_version
    op.execute("ALTER TABLE alembic_version MODIFY version_num VARCHAR(128);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('userstories')
    op.drop_table('proyects')
    # ### end Alembic commands ###
